# Generated by Django 4.0.4 on 2022-05-25 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='headline',
            unique_together={('title', 'image', 'url')},
        ),
    ]
