# Generated by Django 4.0.4 on 2022-05-27 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_headline_unique_together_headline_date_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='headline',
            unique_together={('title', 'image', 'url')},
        ),
        migrations.AlterField(
            model_name='headline',
            name='date',
            field=models.TextField(blank=True, null=True),
        ),
    ]
