# Generated by Django 4.0.4 on 2022-05-27 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_headline_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='headline',
            unique_together={('title', 'image', 'url')},
        ),
        migrations.RemoveField(
            model_name='headline',
            name='date',
        ),
    ]
