# Generated by Django 4.0.4 on 2022-05-27 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_headline_unique_together_remove_headline_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='headline',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='headline',
            name='date',
            field=models.TextField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='headline',
            unique_together={('title', 'image', 'date', 'url')},
        ),
    ]
