# Generated by Django 4.0.5 on 2022-06-22 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_alter_headline_unique_together_headline_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headline',
            name='date',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='headline',
            name='image',
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='headline',
            name='url',
            field=models.TextField(max_length=200),
        ),
    ]
